apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: analytics-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::640494160208:role/analytics-service-role
