apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
images:
  - name: 570814275471.dkr.ecr.us-east-2.amazonaws.com/fiap-fase2/auth-service
    newTag: "1.0.3"
